version: '3.8'

services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mensagens_db
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_SERVER=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mensagens_db
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:password@db/mensagens_db
      - ZAPI_CLIENT_TOKEN=F46f0bb95d1c042f9857c8121a0aca437S
      - ZAPI_INSTANCE_TOKEN=E325327D0022DDAC914CA15B
      - ZAPI_INSTANCE_ID=3ECD22C8F0D83341D160DAD6DC7CFA85
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres_data:
